### ISSUE TITLE
What is this used for? 

### ISSUE THREAD

**Issue by mattpang** [IslePilot/py3_scripts#1]
Sometimes my vscode adds in packages to try and be helpful, was this the case here?

https://github.com/IslePilot/py3_scripts/blob/f62248083050454db259b8a88b3b30acc329ccdb/adsb_utilities/cifp_point.py#L28

**Comment by IslePilot** [comment]
Yes, I see no need for that line.

**Comment by IslePilot** [comment]
Closed
