### ISSUE TITLE
Error in opposite_runway

### ISSUE THREAD

**Issue by Ar-Kareem** [IslePilot/py3_scripts#2]
Hi, 

I tried running `cifp_processor.py` with data from march 2023 and I get the following error 
`UnboundLocalError: local variable 'new_ident' referenced before assignment`
In line 830 in `cifp_processor.py`

I debugged a little bit and found that the function `opposite_runway` is being called with `ident='ALL  '`
However the current code for `opposite_runway` only handles when `ident` is 1,2,4+ characters long and never when it's exactly 3 (as with `ALL  `)

The `airport` variable that has this runway is called `airport='16WI'`
The same airport also has another runway is called `ident='WAY  '` which would also break the code.

Is there an easy fix for this?

I'm not sure if this is helpful at all but I think this is the part where the two runways are located in the CIFP file
![image](https://user-images.githubusercontent.com/65195696/226989075-6ad07de9-deb0-4527-bd90-dd18f2527554.png)

This project is great btw, thanks a lot.

**Comment by Ar-Kareem** [comment]
Currently I simply added the following condition right before calling `opposite_runway` to skip those runways
```
            if len(rw.rstrip()) == 3:
              continue
```
In here
https://github.com/IslePilot/py3_scripts/blob/bc50b7215eb3de886cc1b71f63b8ccdc839b8993/adsb_utilities/cifp_processor.py#L285-L287

Which makes the code run without errors but I'm not sure if this will cause major issues in the output

**Comment by Ar-Kareem** [comment]
also this should be a separate issue but I needed to swap all the "\\\\" in strings related to folders to a "/" for the code to work on my linux machine.

You might want to adopt `pathlib` so you can simply do 

```
from pathlib import Path
root = Path('root_fldr')
sub_fldr =  root / 'sub_fldr_a' / 'sub_sub_fldr_b'
```
and it will work on both windows and linux instead of hardcoding the OS specific separator into the path

**Comment by IslePilot** [comment]
Actually I already fixed this, I just forgot to check it in. The fix is 
there now.

I am curious what you are using the code for?

**Comment by Ar-Kareem** [comment]
Thanks a lot.

I'm trying to train an AI model to be able to understand maps, this is the current project https://github.com/Ar-Kareem/multimodal_infolab
